services:
  - type: web
    name: sully-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn sully_api:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"